using System;
using System.IO;
using static System.Console;

namespace dependadot
{
    class Program
    {
        private static string[] s_patterns = new string[]
    {".csproj", ".fsproj", ".vbproj"};

        static void Main(string[] args)
        {
            var path = string.Empty;

            if (Console.IsInputRedirected)
            {
                var line = In.ReadLine();
                if (line is object)
                {
                    path = line;
                }
                else
                {
                    Error();
                    return;
                }
            }
            else if (args.Length == 1 &&
                Directory.Exists(args[0]))
            {
                path = args[0];
            }
            else
            {
                Error();
                return;
            }

            var printboilerplate = true;

            foreach (var file in Directory.EnumerateFiles(path,"*.*",SearchOption.AllDirectories))
            {
                if (IsProject(file))
                {

                    /* pattern:
                        - package-ecosystem: nuget
                        directory: "/src/netlandingpage"
                        schedule:
                            interval: daily
                        open-pull-requests-limit: 10
                      */

                    var filename = Path.GetFileName(file);
                    var parentDir = Path.GetDirectoryName(file);
                    var relativeDir = string.Empty;

                    if (parentDir == null ||
                        parentDir.Length == path.Length)
                        {
                            relativeDir="/";
                        }
                        else
                        {
                            relativeDir = parentDir.Substring(path.Length).Replace('\\','/');
                        }
                    if (HasDependencies(path, relativeDir, filename))
                    {
                        if (printboilerplate)
                        {
                            PrintBoilerPlate();
                            printboilerplate = false;
                        }
                        WriteLine( 
$@"- package-ecosystem: nuget
  directory: ""{relativeDir}"" # {filename}
  schedule:
    interval: daily
  open-pull-requests-limit: 10");
                    }
                }
            }
        }

        static void PrintBoilerPlate()
        {
            WriteLine(
@"# Generated by https://github.com/richlander/dependadotnet
version: 2
updates:");
        }

        static void Error()
        {
            WriteLine("Must specify a repo root directory as input");
        }

        public static bool IsProject(string filename)
        {
            var p = s_patterns;
            return
                filename.EndsWith(p[0]) |
                filename.EndsWith(p[1]) |
                filename.EndsWith(p[2]);
        }
        
        // This is (hopefully) temporary. The docs repos have too many
        // projects for the parser dependabot uses. More than 100 ecosystem
        // nodes fails. Therefore, filter out all project files that don't
        // have NuGet packages other than the main framework. 
        // See https://github.com/dependabot/feedback/issues/975
        // and https://github.com/dependabot/feedback/issues/976 for
        // feature requests that would enable us to add all
        // projects and update the target framework.
        public static bool HasDependencies(string path, string relativeDir, string fileName)
        {
            var projPath = string.Concat(path, relativeDir);
            projPath = Path.Combine(projPath, fileName);
            string text = File.ReadAllText(projPath);
            return text.Contains("PackageReference");
        }
    }
}
